export const userConstants = {
  REG_REQUEST: "REG_REQUEST",
  REG_SUCCESS: "REG_SUCCESS",
  REG_FAILURE: "REG_FAILURE",

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "USER_LOGIN_FAILURE",

  CREAT_BOOKING_REQUEST: "CREAT_BOOKING_REQUEST",
  CREAT_BOOKING_SUCCESS: "CREAT_BOOKING_SUCCESS",
  CREAT_BOOKING_FAILURE: "CREAT_BOOKING_FAILURE",

  GET_BOOKING_REQUEST: "GET_BOOKING_REQUEST",
  GET_BOOKING_SUCCESS: "GET_BOOKING_SUCCESS",
  GET_BOOKING_FAILURE: "GET_BOOKING_FAILURE",

  LOGOUT: "USER_LOGOUT",

  CLEAR: "CLEAR",
};
